### ISSUE TITLE
Tabs are replaced with spaces in Makefile

### ISSUE THREAD

**Issue by asbjornu** [lee-dohm/tabs-to-spaces#42]
As mentioned in atom/language-make#3, I'm having problems with tabs being replaced with spaces in a `Makefile`. As this causes the Makefile to stop working, it's a rather big problem. I've identified the tabs-to-spaces package as the perpetrator. I've tried to adjust my configuration to:

```yaml
"*":
  "tabs-to-spaces":
    "onSave": "untabify"
"Makefile":
  "tabs-to-spaces":
    "onSave": "tabify"
```

But the `"Makefile"` section seems to be ignored. Tabs are still replaced with spaces in my `Makefile`. Is my configuration invalid?
